config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>
  <ul>
    <% @articles.each do |article| %>
      <li><%= link_to article.title, article_path(article) %></li>
    <% end %>
  </ul>
  <div><%= link_to "Add a new article", new_article_path %></div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>New article</h1>
  <%= form_for(@article) do |f| %>
    <div class="form-group">
      <strong><%= f.label :title %></strong>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <strong><%= f.label :content %></strong>
      <%= f.text_field :content, class: 'form-control' %>
    </div>

    <div class="input"><%= f.submit class: 'btn btn-primary' %></div>
  <% end %>
  <div><%= link_to "Back to list", articles_path %></div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1><%= @article.title %></h1>
  <p><%= @article.content %></p>
  <div><%= link_to "Back to index", articles_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>